import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Sidebar from "./components/sidebar";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KonterKu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-slate-50">
      <body className={inter.className}>
        <div className="lg:flex">
          <Sidebar />
          <div className="w-screen">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
